name: Build Android (Debug)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # NÃO fixar versão. Usar o wrapper do repo.
      - name: Gradle (use wrapper, disable cache)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
          cache-disabled: true
          gradle-home-cache-cleanup: true

      # (Opcional mas MUITO útil) Mostrar qual distributionUrl está no repo
      - name: Show gradle-wrapper.properties
        run: |
          echo "--- gradle/wrapper/gradle-wrapper.properties ---"
          cat gradle/wrapper/gradle-wrapper.properties || true

      # Garantir que não haja cache antigo e forçar wrapper 8.7
      - name: Purge Gradle caches
        run: |
          rm -rf ~/.gradle/wrapper
          rm -rf ~/.gradle/caches
          ./gradlew --no-daemon --version

      - name: Build Debug APK (via wrapper)
        run: ./gradlew --no-daemon clean assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: "**/build/outputs/apk/debug/*.apk"