steps:
  - name: Checkout
  # garante o repositório completo e preserva permissões
    uses: actions/checkout@v4
    with:
      fetch-depth: 0

  - name: Set up JDK 17
    uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: 17

  - name: Mostrar árvore do repo
    run: |
      pwd
      ls -la
      echo "----"
      if [ -d gradle/wrapper ]; then ls -la gradle/wrapper; fi
      echo "----"
      find . -maxdepth 3 -name "build.gradle*" -print

  # Corrige finais de linha CRLF do gradlew (erro sh\r)
  - name: Fix CRLF in gradlew
    run: |
      if [ -f gradlew ]; then
        sed -i -e 's/\r$//' gradlew
      fi

  - name: Garantir permissão de execução no gradlew
    run: |
      if [ -f gradlew ]; then
        chmod +x gradlew
      fi

  - name: Forçar Gradle 8.10 (wrapper)
    uses: gradle/gradle-build-action@v3
    with:
      arguments: wrapper --gradle-version 8.10 --distribution-type bin

  - name: Conferir versão do Gradle
    run: |
      ./gradlew --version || true

  - name: Listar tasks disponíveis
    run: |
      ./gradlew tasks --all || true

  # Tente compilar na raiz padrão
  - name: Build (assembleDebug genérico)
    run: |
      set -e
      if [ -f settings.gradle ] || [ -f settings.gradle.kts ]; then
        # Se existir módulo "app", use :app:assembleDebug, senão tente assembleDebug na raiz
        if grep -q ":app" settings.gradle* 2>/dev/null; then
          ./gradlew clean :app:assembleDebug
        else
          ./gradlew clean assembleDebug
        fi
      else
        echo "settings.gradle não encontrado na raiz. Tentando procurar módulo..."
        # Descobrir módulo com plugin application
        MOD=$(grep -RIl "com.android.application" -n | sed 's|/build.gradle.*||' | sed 's|^\./||' | head -n1)
        echo "Módulo detectado: $MOD"
        if [ -n "$MOD" ]; then
          ./gradlew clean :"$MOD":assembleDebug
        else
          echo "Não foi possível detectar módulo. Falha."
          exit 1
        fi
      fi

  - name: Upload APK artifact
    uses: actions/upload-artifact@v4
    with:
      name: app-debug
      path: '**/build/outputs/apk/debug/*.apk'