name: Build CaixaForte (Debug APK)
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 17 }
      - uses: android-actions/setup-android@v3
      - name: Install Android platforms and build-tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"
      - uses: gradle/gradle-build-action@v3
        with: { gradle-version: 8.10, arguments: "wrapper --gradle-version 8.10" }
      - run: chmod +x gradlew
      - uses: gradle/gradle-build-action@v3
        with: { arguments: ":app:assembleDebug --stacktrace" }
      - uses: actions/upload-artifact@v4
        with: { name: caixaforte-debug, path: app/build/outputs/apk/debug/*.apk }
